---
- name: "Install Wordpress in nginx server"
  become: true
  hosts: ubuntu
  vars:
    wp_url: "https://wordpress.org/latest.tar.gz"
  vars_files:
    - db.vars
    - vnginx.vars
  tasks:
    - name: "Update apt repo and cache"
      apt:
        force_apt_get: yes
        update_cache: yes
        upgrade: true
        cache_valid_time: 86400
